export const HEADER_HEIGHT = '3.5em';
export const HEADER_NAV_EXPAND_COLLAPSE_TIME_MS = 500;
export const HEADER_NAV_EXPAND_COLLAPSE_TIME = `${HEADER_NAV_EXPAND_COLLAPSE_TIME_MS/1000}s`;
export const HEADER_SETTINGS_EXPAND_COLLAPSE_TIME_MS = 400;
export const HEADER_SETTINGS_EXPAND_COLLAPSE_TIME = `${HEADER_SETTINGS_EXPAND_COLLAPSE_TIME_MS/1000}s`;

export enum ZIndexes {
  BACKGROUND = -1,
  HEADER = 10,
  POPUP = 20,
  MODAL = 30
}